version: '3.8'

services:
   nestapp:
     build: ./
    #  image: fgp555/homework-m4:latest
     ports:
       - "3001:3000"
     env_file:
       - .env
     depends_on:
       - postgresdb

   postgresdb:
     image: postgres
     volumes:
       - pgdata:/var/lib/postgresql/data
     env_file:
       - .env

volumes:
  pgdata: